version: '3.7'

services:
  
  elasticsearch:
    container_name: 'dmtools.elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - 9200:9200
    volumes:
      - /usr/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - internal

  kibana:
    container_name: 'dmtools.kibana'
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch
    networks:
      - internal
  
  postgres:
    container_name: 'dmtools.postgres'
    restart: always
    image: postgres
    build:
      context: .\postgres
      dockerfile: .dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=dmtoolsdb_identity,dmtoolsdb_users,dmtoolsdb
    networks:
      - internal
  
  identity-server:
    container_name: 'identity.server'
    image: 'identity.server'
    build:
      context: .\API\Identity
      dockerfile: dev.dockerfile
    ports:
      - "8000:443"
    volumes:
      - /usr/https:/https
    depends_on:
      - "postgres"
      - "elasticsearch"
      - "kibana"
    networks:
      - internal

  api-users:
    container_name: 'dmtools.users'
    image: 'dmtools.users'
    build:
      context: .\API\Users
      dockerfile: dev.dockerfile
    ports:
      - "8001:443"
    volumes:
      - /usr/https:/https
    depends_on:
      - "postgres"
      - "identity-server"
      - "elasticsearch"
      - "kibana"
    networks:
      - internal

  web:
    container_name: 'dmtools.web'
    image: 'dmtools.web'
    build:
      context: .\Web
      dockerfile: dev.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/https:/https
    depends_on:
      - "postgres"
      - "identity-server"
      - "api-users"
      - "elasticsearch"
      - "kibana"
    networks:
      - internal  
      
networks:
  internal:
    driver: bridge