output.elasticsearch:
  hosts: ["dmtools.elasticsearch"]
  username: "elastic"
  password: "123qwe!E"
  
setup.kibana:
  host: "dmtools.kibana"
  
filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*-json.log'
      
processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

logging.json: true
logging.metrics.enabled: false